### ISSUE TITLE
Logger to service, repositories input and  output method 

### ISSUE THREAD

**Issue by kamarros** [slawekpaciorek/oma2nd#48]
- [x] AddressServiceImplementation and DAO
Sample:

> logger.warn("Exposing all the address list");

> logger.info("Address` save from the service layer!");

> logger.info("Get address for id from the service layer");

> logger.warn("Exposing update address from the service layer");

- [x] CompanyServiceImplementation and DAO

- [x] ProductServiceImplementation and DAO

- [x] UserServiceImplementation and DAO

**Comment by kamarros** [comment]
25.01.2021
_Flow diagram **addUser(User user)**_
![loggerLogic](https://user-images.githubusercontent.com/66215467/105897049-efe1d080-6017-11eb-8249-4e8499e915de.png)

_Sample code:_
@Override
    @Transactional
    public void addUser(User user) {
        logger.warn("Save user from service layer");
        if (user != null) {
            userDAO.saveUser(user);
            logger.info("Save user is success!");
        } else {
            logger.error("Trying save user from service layer FAILED!");
        }
    }

_Condition  #problem:_
 if (user != null) -> **is it enough???**


27.01.2021
**1. Create class own exeption:**
package com.oma.exceptions;

    public class NoElementFoundExceptions extends Exception {
    public NoElementFoundExceptions(String message, Throwable cause) {
        super(message, cause);
    }
}


**2. Use in service layer:**

    @Override
    @Transactional
    public void addUser(User user) throws NoElementFoundExceptions {
        logger.warn("Save user from service layer");
        try {
            userDAO.saveUser(user);
            logger.info("Save user is success!");
        } catch (NullPointerException e){
            logger.error("Trying save user from service layer FAILED!");
            throw new NoElementFoundExceptions("Save user FILED!",e);
        }
    }

**3.Use in repo layer:**

    @Override
    @Transactional
    public void saveUser(User user) throws NoElementFoundExceptions {
        logger.info("Trying to save the user to the database from the repositories layer!");
        try {
            Session factoryCurrentSession = sessionFactory.getCurrentSession();
            factoryCurrentSession.save(user);
            logger.info("Save user is success!");
        } catch (NullPointerException e){
            logger.error("Trying save user from repositories layer FAILED!");
            throw new NoElementFoundExceptions("Save user FILED",e);
        }
    }

**4. Add adnotation @SneakyThrows in UserServiceTest**

    @SneakyThrows
    @Test
    public void shouldSaveUserInDB(){
        //given
        User expected = new User();
        expected.setPassword("Testy");
        expected.setName("Kamil");
        expected.setUsername("Kamil");
        expected.setMobilePhone(788788788);
        //when
        userService.addUser(expected);
        User result = (User)session.createQuery("from User user where user.username=:username and user.name=:name " +
                "and user.mobilePhone=:mobilPhone")
                .setParameter("username",expected.getUsername())
                .setParameter("name",expected.getName())
                .setParameter("mobilPhone",expected.getMobilePhone())
                .getSingleResult();
        //then
        Assertions.assertEquals(result,expected);

28.01.2021

**1. Add dependencies to pom.xml:**

                <dependency>
			<groupId>org.aspectj</groupId>
			<artifactId>aspectjrt</artifactId>
			<version>1.9.6</version>
		</dependency>
		<dependency>
			<groupId>org.aspectj</groupId>
			<artifactId>aspectjweaver</artifactId>
			<version>1.9.6</version>
		</dependency>


**2. Create class LoggingAspect in NEW package**

    @Aspect
    @Component
    @EnableAspectJAutoProxy
    @Slf4j
    public class LoggingAspect {
    @Pointcut("execution(* com.oma..*(..))")
    private void anyPublicMethod(){
    }
    @Before("anyPublicMethod()")
    public void beforeAnyPublicMethod(JoinPoint joinPoint){
        log.info(" :: before :: " + joinPoint.getSignature().getName());
    }
    @After("anyPublicMethod()")
    public void afterAnyPublicMethod(JoinPoint joinPoint){
        log.info(" :: after :: " + joinPoint.getSignature().getName());
    }
}

**3. Add adnotation @EnableAspectJAutoProxy(proxyTargetClass=true)**

      @SpringBootApplication
      @EnableAspectJAutoProxy(proxyTargetClass=true)
       public class OrderManagementApplication {
       private static Logger log = LoggerFactory.getLogger(OrderManagementApplication.class);
	public static void main(String[] args) {
		log.trace("Application is running");
		SpringApplication.run(OrderManagementApplication.class, args);
	}
}

**Comment by slawekpaciorek** [comment]
I am nto sure but I think we should use try/catch block and use als exception. I need some time to think about some simple solution. Try to concern to makr simple logs with input and output, ex ( void save(){ input log / business logic / output log}
